[package]
name = "rura-grammar"
version = "0.1.0"
edition = "2021"

[dependencies]
winnow = "0.6.2"

[dependencies.rura-core]
path = "../rura-core"

[dependencies.rura-parsing]
path = "../rura-parsing"
