name: Rust Build
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
env:
  CARGO_TERM_COLOR: always
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Initialize Rustup
        run: |
          rustup toolchain install nightly --component rustfmt clippy --profile minimal --force
          rustup override set nightly
      - name: Run build
        run: cargo build --verbose
      - name: Run rustfmt
        run: cargo fmt --all -- --check
      - name: Run clippy
        run: cargo clippy --all -- -D warnings
      - name: Build
        run: cargo build --release --verbose
      - name: Run debug tests
        run: cargo test --verbose
      - name: Run release tests
        run: cargo test --verbose --release
